[workspace]
members = [
  "anvil",
  "pulley",
  "quench/examples/*",
  "quench/quench-*",
  "riveter",
  "switchboard/*",
  "toolbox",
  "warehouse/*",
  "welder",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Paweł Walus <pawel.walus@protonmail.com>"]
homepage = "https://github.com/lorehaven/forge"
repository = "https://github.com/lorehaven/forge"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
actix-http = { version = "3.12" }
actix-service = { version = "2.0" }
actix-web = { version = "4.13", features = ["rustls-0_23"] }
actix-ws = { version = "0.4" }
anyhow = { version = "1.0" }
async-trait = { version = "0.1" }
axum = { version = "0.8", features = ["json"] }
base64 = { version = "0.22" }
chrono = { version = "0.4" }
clap = { version = "4.6", features = ["derive"] }
crossterm = { version = "0.29" }
cucumber = { version = "0.23" }
dotenvy = { version = "0.15" }
envmnt = { version = "0.10" }
fluent-syntax = { version = "0.12" }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
gguf = { version = "0.1" }
html5ever = { version = "0.39" }
hmac = { version = "0.13" }
jsonwebtoken = { version = "10.4", features = ["rust_crypto"] }
markup5ever_rcdom = { version = "0.39.0" }
minijinja = { version = "2.20", features = ["loader", "serde"] }
moka = { version = "0.12", features = ["sync"] }
quench-cli = { path = "quench/quench-cli" }
quench-srv = { path = "quench/quench-srv" }
quench-web = { path = "quench/quench-web" }
regex = { version = "1.12" }
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "stream",
  "rustls",
] }
rustls = { version = "0.23" }
rustls-pemfile = { version = "2" }
rustyline = { version = "18.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
shlex = { version = "2.0" }
serde_yaml = { version = "0.9.34" }
semver = { version = "1.0" }
sha2 = { version = "0.11" }
strum = { version = "0.28" }
strum_macros = { version = "0.28" }
thiserror = { version = "2.0" }
tokio = { version = "1.52", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
toml = { version = "1.1" }
toml_edit = { version = "0.25" }
tower-http = { version = "0.6", features = ["fs"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
utoipa = { version = "5.5", features = ["macros"] }
utoipa-swagger-ui = { version = "9.0", features = ["actix-web"] }
uuid = { version = "1.23", features = ["v4"] }
walkdir = { version = "2.5" }
which = { version = "8.0" }
zip = { version = "8.6" }
