[[migrations]]
id = "0001-initial-users-schema"
author = "quench-srv"

[[migrations.changes]]
createSchema = { name = "warehouse" }

[[migrations.changes]]
createTable = { schema = "warehouse", name = "users", columns = [
    { name = "username", data_type = "TEXT", primary_key = true, nullable = false },
    { name = "password", data_type = "TEXT", nullable = false },
    { name = "roles", data_type = "JSONB", nullable = false }
]}

