use quench_web::prelude::CssRule;

pub fn chat_rules() -> Vec<CssRule> {
    vec![
        CssRule::new(".content")
            .property("height", "calc(100vh - 4.5rem) !important")
            .property("padding", "0 !important")
            .property("max-width", "none !important"),
        CssRule::new(".content-inner")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("max-width", "none !important")
            .property("align-items", "stretch !important")
            .property("padding", "0 !important"),
        CssRule::new(".page")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("display", "flex !important")
            .property("flex-direction", "column !important"),
        CssRule::new(".home-content")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("display", "flex !important")
            .property("flex-direction", "column !important"),
        CssRule::new(".chat-container")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("justify-content", "flex-start")
            .property("flex", "1")
            .property("height", "100%")
            .property("width", "100%")
            .property("max-width", "none")
            .property("margin", "0 auto")
            .property("background", "transparent")
            .property("position", "relative")
            .property("overflow", "hidden"),
        CssRule::new(".chat-history")
            .property("flex", "1")
            .property("overflow-y", "auto")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("width", "100%"),
        CssRule::new(".chat-history-spacer").property("flex", "1"),
        CssRule::new(".chat-message")
            .property("padding", "1rem 0")
            .property("width", "100%")
            .property("display", "flex")
            .property("justify-content", "center"),
        CssRule::new(".message-inner")
            .property("max-width", "50rem")
            .property("width", "95%")
            .property("display", "flex"),
        CssRule::new(".message-ai .message-inner").property("justify-content", "flex-start"),
        CssRule::new(".message-user .message-inner").property("justify-content", "flex-end"),
        CssRule::new(".message-content")
            .property("font-size", "1.1rem")
            .property("line-height", "1.6")
            .property("padding", "0.5rem 1rem")
            .property("border-radius", "1rem")
            .property("word-break", "break-word")
            .property("text-align", "left")
            .property("white-space", "pre-wrap")
            .property("overflow-wrap", "anywhere")
            .property("max-width", "100%")
            .property("width", "100%")
            .property("user-select", "text"),
        CssRule::new(".message-content pre")
            .property("margin", "0.5rem 0")
            .property("white-space", "pre-wrap")
            .property("word-break", "break-word")
            .property("overflow-wrap", "anywhere")
            .property("font-family", "inherit")
            .property("font-size", "inherit")
            .property("color", "inherit")
            .property("max-width", "100%"),
        CssRule::new(".code-block")
            .property("background", "rgba(0, 0, 0, 0.3)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "0.75rem")
            .property("margin", "1rem 0")
            .property("overflow", "hidden")
            .property("display", "flex")
            .property("flex-direction", "column"),
        CssRule::new(".code-header")
            .property("display", "flex")
            .property("justify-content", "space-between")
            .property("align-items", "center")
            .property("padding", "0.4rem 1rem")
            .property("background", "rgba(0, 0, 0, 0.2)")
            .property("border-bottom", "1px solid var(--bs-gray-700)"),
        CssRule::new(".code-lang")
            .property("font-family", "monospace")
            .property("font-size", "0.65rem")
            .property("text-transform", "uppercase")
            .property("color", "var(--bs-gray-500)")
            .property("letter-spacing", "0.05rem"),
        CssRule::new(".copy-btn")
            .property("background", "transparent")
            .property("border", "1px solid var(--bs-gray-600)")
            .property("color", "var(--bs-gray-400)")
            .property("border-radius", "0.4rem")
            .property("padding", "0.2rem 0.6rem")
            .property("font-size", "0.75rem")
            .property("cursor", "pointer")
            .property("display", "inline-flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("gap", "0.4rem")
            .property("height", "1.75rem")
            .property("transition", "all 0.2s")
            .child(CssRule::new("span").property("padding", "0 0.4rem"))
            .child(
                CssRule::new(":hover")
                    .property("background", "var(--bs-gray-700)")
                    .property("color", "white")
                    .property("border-color", "var(--bs-gray-400)"),
            )
            .child(
                CssRule::new(".success")
                    .property("border-color", "var(--bs-success)")
                    .property("color", "var(--bs-success)"),
            ),
        CssRule::new(".code-block pre")
            .property("margin", "0 !important")
            .property("padding", "1rem")
            .property("background", "transparent !important")
            .property("border", "none !important")
            .property("border-radius", "0 !important"),
        CssRule::new(".code-block pre code")
            .property("display", "block")
            .property("background", "transparent !important")
            .property("border", "none !important")
            .property("padding", "0 !important")
            .property("margin", "0 !important")
            .property("font-family", "'Fira Code', 'Courier New', monospace")
            .property("font-size", "1rem")
            .property("text-align", "left")
            .property("overflow-x", "auto"),
        CssRule::new(".message-content table")
            .property("width", "100%")
            .property("border-collapse", "collapse")
            .property("margin", "1rem 0")
            .property("font-size", "0.95rem")
            .property("line-height", "1.4")
            .property("background", "rgba(255, 255, 255, 0.02)")
            .property("border-radius", "0.5rem")
            .property("overflow", "hidden"),
        CssRule::new(".message-content th")
            .property("background", "rgba(255, 255, 255, 0.05)")
            .property("color", "white")
            .property("text-align", "left")
            .property("padding", "0.75rem")
            .property("border-bottom", "2px solid var(--bs-gray-700)"),
        CssRule::new(".message-content td")
            .property("padding", "0.75rem")
            .property("border-bottom", "1px solid var(--bs-gray-800)")
            .property("color", "var(--bs-gray-300)"),
        CssRule::new(".message-content tr:last-child td").property("border-bottom", "none"),
        CssRule::new(".message-content tr:nth-child(even)")
            .property("background", "rgba(255, 255, 255, 0.01)"),
        CssRule::new(".inline-code")
            .property("background", "rgba(255, 255, 255, 0.1)")
            .property("color", "var(--bs-primary)")
            .property("padding", "0.1rem 0.3rem")
            .property("border-radius", "0.3rem")
            .property("font-family", "'Fira Code', monospace")
            .property("font-size", "0.9em"),
        CssRule::new(".message-ai .message-content")
            .property("background", "transparent")
            .property("color", "var(--bs-gray-200)")
            .property("max-width", "100%"),
        CssRule::new(".message-user .message-content")
            .property("background", "rgba(255, 255, 255, 0.05)")
            .property("color", "white")
            .property("max-width", "85%"),
        CssRule::new(".chat-navigation")
            .property("position", "absolute")
            .property("right", "0.75rem")
            .property("top", "50%")
            .property("transform", "translateY(-50%)")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("gap", "0.25rem") // Tighter gap for more dots
            .property("z-index", "100")
            .property("padding", "1rem 0.5rem")
            .property("background", "rgba(0,0,0,0.2)")
            .property("border-radius", "1rem")
            .property("backdrop-filter", "blur(8px)")
            .property("overflow", "visible"), // CRITICAL: Allow tooltips to pop out
        CssRule::new(".nav-dot")
            .property("width", "1.5rem") // Increased hit area
            .property("height", "1rem")
            .property("display", "flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("cursor", "pointer")
            .property("position", "relative")
            .property("transition", "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"),
        CssRule::new(".nav-dot::before")
            .property("content", "''")
            .property("width", "0.4rem")
            .property("height", "0.4rem")
            .property("border-radius", "50%")
            .property("background", "var(--bs-gray-600)")
            .property("transition", "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"),
        CssRule::new(".nav-dot:hover::before")
            .property("background", "var(--bs-gray-100)")
            .property("transform", "scale(1.5)"),
        CssRule::new(".nav-dot:hover .nav-tooltip")
            .property("visibility", "visible")
            .property("opacity", "1")
            .property("transform", "translateY(-50%) translateX(-0.5rem)"),
        CssRule::new(".nav-tooltip")
            .property("visibility", "hidden")
            .property("opacity", "0")
            .property("position", "absolute")
            .property("right", "100%") // Relative to the nav-dot
            .property("top", "50%")
            .property("transform", "translateY(-50%) translateX(0)")
            .property("background", "var(--bs-gray-800)")
            .property("color", "white")
            .property("padding", "0.4rem 0.8rem")
            .property("border-radius", "0.5rem")
            .property("font-size", "0.75rem")
            .property("white-space", "nowrap")
            .property("pointer-events", "none")
            .property("transition", "all 0.2s")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("box-shadow", "0 0.5rem 1rem rgba(0,0,0,0.3)")
            .property("z-index", "1000"),
        CssRule::new(".nav-dot.active::before")
            .property("background", "var(--bs-gray-100)")
            .property("width", "0.4rem")
            .property("height", "1.25rem")
            .property("border-radius", "0.25rem")
            .property("content", "''"),
        CssRule::new(".chat-input-wrapper")
            .property("flex", "0 0 auto")
            .property("width", "100%")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("margin", "0")
            .property("padding", "2rem 0")
            .property("background", "transparent"),
        CssRule::new(".chat-input-area-container")
            .property("max-width", "50rem")
            .property("width", "95%")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("margin", "0 auto")
            .property("gap", "0.5rem"),
        CssRule::new(".chat-input-area")
            .property("background", "var(--bs-gray-800)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "1.5rem")
            .property("padding", "0.5rem 1.25rem")
            .property("display", "flex")
            .property("align-items", "flex-end")
            .property("gap", "0.75rem")
            .property("box-shadow", "0 0.5rem 2rem rgba(0,0,0,0.5)"),
        CssRule::new(".chat-input")
            .property("flex", "1")
            .property("background", "transparent")
            .property("border", "none")
            .property("color", "white")
            .property("padding", "0.75rem 0")
            .property("font-size", "1.1rem")
            .property("line-height", "1.5rem")
            .property("outline", "none")
            .property("resize", "none")
            .property("min-height", "3rem")
            .property("max-height", "22.5rem")
            .property("overflow-y", "auto"),
        CssRule::new(".chat-send-btn")
            .property("background", "transparent")
            .property("color", "white")
            .property("border", "none")
            .property("width", "2.25rem")
            .property("height", "2.25rem")
            .property("border-radius", "0.75rem")
            .property("display", "flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("cursor", "pointer")
            .property("margin-bottom", "0.35rem")
            .property("transition", "transform 0.1s")
            .child(CssRule::new(":hover").property("transform", "scale(1.05)"))
            .child(CssRule::new(":active").property("transform", "scale(0.95)")),
        CssRule::new(".chat-input-extras")
            .property("display", "flex")
            .property("justify-content", "flex-start")
            .property("padding", "0 1rem"),
        CssRule::new(".model-selector")
            .property("background", "var(--bs-gray-800)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("color", "var(--bs-gray-400)")
            .property("border-radius", "0.5rem")
            .property("padding", "0.25rem 0.75rem")
            .property("font-size", "0.85rem")
            .property("outline", "none")
            .property("cursor", "pointer")
            .child(CssRule::new(":hover").property("border-color", "var(--bs-gray-500)"))
            .child(CssRule::new(":focus").property("border-color", "var(--bs-primary)")),
    ]
}
