use quench_web::prelude::CssRule;

pub fn chat_rules() -> Vec<CssRule> {
    vec![
        CssRule::new(".content")
            .property("height", "calc(100vh - 4.5rem) !important")
            .property("padding", "0 !important")
            .property("max-width", "none !important"),
        CssRule::new(".content-inner")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("max-width", "none !important")
            .property("align-items", "stretch !important")
            .property("padding", "0 !important"),
        CssRule::new(".page")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("display", "flex !important")
            .property("flex-direction", "column !important"),
        CssRule::new(".home-content")
            .property("height", "100% !important")
            .property("width", "100% !important")
            .property("display", "flex !important")
            .property("flex-direction", "column !important"),
        CssRule::new(".chat-container")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("justify-content", "flex-start")
            .property("flex", "1")
            .property("height", "100%")
            .property("width", "100%")
            .property("max-width", "none")
            .property("margin", "0 auto")
            .property("background", "transparent")
            .property("position", "relative")
            .property("overflow", "hidden"),
        CssRule::new(".chat-history")
            .property("flex", "1")
            .property("overflow-y", "auto")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("width", "100%"),
        CssRule::new(".chat-history-spacer").property("flex", "1"),
        CssRule::new(".chat-message")
            .property("padding", "1rem 0")
            .property("width", "100%")
            .property("display", "flex")
            .property("justify-content", "center"),
        CssRule::new(".message-inner")
            .property("max-width", "50rem")
            .property("width", "95%")
            .property("display", "flex")
            .property("flex-direction", "column"),
        CssRule::new(".message-ai .message-inner").property("align-items", "flex-start"),
        CssRule::new(".message-user .message-inner").property("align-items", "flex-end"),
        CssRule::new(".message-content")
            .property("font-size", "1.1rem")
            .property("line-height", "1.6")
            .property("padding", "0.5rem 1rem")
            .property("border-radius", "1rem")
            .property("word-break", "break-word")
            .property("text-align", "left")
            .property("overflow-wrap", "anywhere")
            .property("max-width", "100%")
            .property("width", "100%")
            .property("user-select", "text"),
        CssRule::new(".message-content p").property("margin", "0 0 1rem 0"),
        CssRule::new(".message-content p:last-child").property("margin-bottom", "0"),
        CssRule::new(".message-content pre")
            .property("margin", "0.5rem 0")
            .property("white-space", "pre-wrap")
            .property("word-break", "break-word")
            .property("overflow-wrap", "anywhere")
            .property("font-family", "inherit")
            .property("font-size", "inherit")
            .property("color", "inherit")
            .property("max-width", "100%"),
        CssRule::new(".code-block")
            .property("background", "rgba(0, 0, 0, 0.3)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "0.75rem")
            .property("margin", "1rem 0")
            .property("overflow", "hidden")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("width", "100%"),
        CssRule::new(".code-header")
            .property("display", "flex")
            .property("justify-content", "space-between")
            .property("align-items", "center")
            .property("padding", "0.4rem 1rem")
            .property("background", "rgba(0, 0, 0, 0.2)")
            .property("border-bottom", "1px solid var(--bs-gray-700)"),
        CssRule::new(".code-lang")
            .property("font-family", "monospace")
            .property("font-size", "0.65rem")
            .property("text-transform", "uppercase")
            .property("color", "var(--bs-gray-500)")
            .property("letter-spacing", "0.05rem"),
        CssRule::new(".copy-btn")
            .property("background", "transparent")
            .property("border", "1px solid var(--bs-gray-600)")
            .property("color", "var(--bs-gray-400)")
            .property("border-radius", "0.4rem")
            .property("padding", "0.2rem 0.6rem")
            .property("font-size", "0.75rem")
            .property("cursor", "pointer")
            .property("display", "inline-flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("gap", "0.4rem")
            .property("height", "1.75rem")
            .property("transition", "all 0.2s")
            .child(CssRule::new("span").property("padding", "0 0.4rem"))
            .child(
                CssRule::new(":hover")
                    .property("background", "var(--bs-gray-700)")
                    .property("color", "white")
                    .property("border-color", "var(--bs-gray-400)"),
            )
            .child(
                CssRule::new(".success")
                    .property("border-color", "var(--bs-success)")
                    .property("color", "var(--bs-success)"),
            ),
        CssRule::new(".code-block pre")
            .property("margin", "0 !important")
            .property("padding", "1rem")
            .property("background", "transparent !important")
            .property("border", "none !important")
            .property("border-radius", "0 !important"),
        CssRule::new(".code-block pre code")
            .property("display", "block")
            .property("background", "transparent !important")
            .property("border", "none !important")
            .property("padding", "0 !important")
            .property("margin", "0 !important")
            .property("font-family", "'Fira Code', 'Courier New', monospace")
            .property("font-size", "1rem")
            .property("text-align", "left")
            .property("overflow-x", "auto"),
        CssRule::new(".message-content table")
            .property("width", "100%")
            .property("border-collapse", "collapse")
            .property("margin", "1rem 0")
            .property("font-size", "0.95rem")
            .property("line-height", "1.4")
            .property("background", "rgba(255, 255, 255, 0.02)")
            .property("border-radius", "0.5rem")
            .property("overflow", "hidden"),
        CssRule::new(".message-content th")
            .property("background", "rgba(255, 255, 255, 0.05)")
            .property("color", "white")
            .property("text-align", "left")
            .property("padding", "0.75rem")
            .property("border-bottom", "2px solid var(--bs-gray-700)"),
        CssRule::new(".message-content td")
            .property("padding", "0.75rem")
            .property("border-bottom", "1px solid var(--bs-gray-800)")
            .property("color", "var(--bs-gray-300)"),
        CssRule::new(".message-content tr:last-child td").property("border-bottom", "none"),
        CssRule::new(".message-content tr:nth-child(even)")
            .property("background", "rgba(255, 255, 255, 0.01)"),
        CssRule::new(".inline-code")
            .property("background", "rgba(255, 255, 255, 0.1)")
            .property("color", "var(--bs-primary)")
            .property("padding", "0.1rem 0.3rem")
            .property("border-radius", "0.3rem")
            .property("font-family", "'Fira Code', monospace")
            .property("font-size", "0.9em"),
        CssRule::new(".message-ai .message-content")
            .property("background", "transparent")
            .property("color", "var(--bs-gray-200)")
            .property("max-width", "100%"),
        CssRule::new(".message-user .message-content")
            .property("background", "rgba(255, 255, 255, 0.05)")
            .property("color", "white")
            .property("max-width", "85%"),
        CssRule::new(".message-content h1")
            .property("font-size", "1.8rem")
            .property("margin", "1.2rem 0 0.6rem 0")
            .property("font-weight", "600"),
        CssRule::new(".message-content h2")
            .property("font-size", "1.5rem")
            .property("margin", "1.1rem 0 0.5rem 0")
            .property("font-weight", "600"),
        CssRule::new(".message-content h3")
            .property("font-size", "1.3rem")
            .property("margin", "1rem 0 0.5rem 0")
            .property("font-weight", "600"),
        CssRule::new(".message-content h4, .message-content h5, .message-content h6")
            .property("font-size", "1.1rem")
            .property("margin", "0.9rem 0 0.4rem 0")
            .property("font-weight", "600"),
        CssRule::new(".message-content ul, .message-content ol")
            .property("margin", "0 0 1rem 0")
            .property("padding-left", "1.5rem"),
        CssRule::new(".message-content li").property("margin-bottom", "0.25rem"),
        CssRule::new(".message-content li::marker").property("color", "var(--bs-primary)"),
        CssRule::new(".message-content hr")
            .property("margin", "1.5rem 0")
            .property("border", "none")
            .property("border-top", "1px solid var(--bs-gray-700)"),
        CssRule::new(".chat-navigation")
            .property("position", "absolute")
            .property("right", "0.75rem")
            .property("top", "50%")
            .property("transform", "translateY(-50%)")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("gap", "0.25rem") // Tighter gap for more dots
            .property("z-index", "100")
            .property("padding", "1rem 0.5rem")
            .property("background", "rgba(0,0,0,0.2)")
            .property("border-radius", "1rem")
            .property("backdrop-filter", "blur(8px)")
            .property("overflow", "visible"), // CRITICAL: Allow tooltips to pop out
        CssRule::new(".nav-dot")
            .property("width", "1.5rem") // Increased hit area
            .property("height", "1rem")
            .property("display", "flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("cursor", "pointer")
            .property("position", "relative")
            .property("transition", "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"),
        CssRule::new(".nav-dot::before")
            .property("content", "''")
            .property("width", "0.4rem")
            .property("height", "0.4rem")
            .property("border-radius", "50%")
            .property("background", "var(--bs-gray-600)")
            .property("transition", "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"),
        CssRule::new(".nav-dot:hover::before")
            .property("background", "var(--bs-gray-100)")
            .property("transform", "scale(1.5)"),
        CssRule::new(".nav-dot:hover .nav-tooltip")
            .property("visibility", "visible")
            .property("opacity", "1")
            .property("transform", "translateY(-50%) translateX(-0.5rem)"),
        CssRule::new(".nav-tooltip")
            .property("visibility", "hidden")
            .property("opacity", "0")
            .property("position", "absolute")
            .property("right", "100%") // Relative to the nav-dot
            .property("top", "50%")
            .property("transform", "translateY(-50%) translateX(0)")
            .property("background", "var(--bs-gray-800)")
            .property("color", "white")
            .property("padding", "0.4rem 0.8rem")
            .property("border-radius", "0.5rem")
            .property("font-size", "0.75rem")
            .property("white-space", "nowrap")
            .property("pointer-events", "none")
            .property("transition", "all 0.2s")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("box-shadow", "0 0.5rem 1rem rgba(0,0,0,0.3)")
            .property("z-index", "1000"),
        CssRule::new(".nav-dot.active::before")
            .property("background", "var(--bs-gray-100)")
            .property("width", "0.4rem")
            .property("height", "1.25rem")
            .property("border-radius", "0.25rem")
            .property("content", "''"),
        CssRule::new(".chat-input-wrapper")
            .property("flex", "0 0 auto")
            .property("width", "100%")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("margin", "0")
            .property("padding", "2rem 0")
            .property("background", "transparent"),
        CssRule::new(".chat-input-area-container")
            .property("max-width", "50rem")
            .property("width", "95%")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("margin", "0 auto")
            .property("gap", "0.5rem"),
        CssRule::new(".chat-input-area")
            .property("background", "var(--bs-gray-800)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "1.5rem")
            .property("padding", "0.5rem 1.25rem")
            .property("display", "flex")
            .property("align-items", "flex-end")
            .property("gap", "0.75rem")
            .property("box-shadow", "0 0.5rem 2rem rgba(0,0,0,0.5)"),
        CssRule::new(".chat-input")
            .property("flex", "1")
            .property("background", "transparent")
            .property("border", "none")
            .property("color", "white")
            .property("padding", "0.75rem 0")
            .property("font-size", "1.1rem")
            .property("line-height", "1.5rem")
            .property("outline", "none")
            .property("resize", "none")
            .property("min-height", "3rem")
            .property("max-height", "22.5rem")
            .property("overflow-y", "auto"),
        CssRule::new(".chat-send-btn")
            .property("background", "transparent")
            .property("color", "white")
            .property("border", "none")
            .property("width", "2.25rem")
            .property("height", "2.25rem")
            .property("border-radius", "0.75rem")
            .property("display", "flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("cursor", "pointer")
            .property("margin-bottom", "0.35rem")
            .property("transition", "transform 0.1s")
            .child(CssRule::new(":hover").property("transform", "scale(1.05)"))
            .child(CssRule::new(":active").property("transform", "scale(0.95)")),
        CssRule::new(".chat-input-extras")
            .property("display", "flex")
            .property("justify-content", "flex-start")
            .property("padding", "0 1rem"),
        CssRule::new(".model-selector")
            .property("background", "var(--bs-gray-800)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("color", "var(--bs-gray-400)")
            .property("border-radius", "0.5rem")
            .property("padding", "0.25rem 0.75rem")
            .property("font-size", "0.85rem")
            .property("outline", "none")
            .property("cursor", "pointer")
            .child(CssRule::new(":hover").property("border-color", "var(--bs-gray-500)"))
            .child(CssRule::new(":focus").property("border-color", "var(--bs-primary)")),
        CssRule::new(".no-model-warning")
            .property("display", "flex")
            .property("align-items", "center")
            .property("gap", "0.5rem")
            .property("background", "rgba(220, 53, 69, 0.1)")
            .property("border", "1px solid rgba(220, 53, 69, 0.3)")
            .property("color", "#ea868f")
            .property("padding", "0.75rem 1.25rem")
            .property("border-radius", "1rem")
            .property("font-size", "0.9rem")
            .property("margin-bottom", "0.25rem")
            .property("box-shadow", "0 0.25rem 1rem rgba(0,0,0,0.3)"),
        CssRule::new(".chat-input-area-container.disabled .chat-input-area")
            .property("opacity", "0.6")
            .property("border-color", "rgba(220, 53, 69, 0.2)"),
        CssRule::new(".chat-input:disabled")
            .property("color", "var(--bs-gray-600) !important")
            .property("cursor", "not-allowed"),
        CssRule::new(".chat-send-btn:disabled")
            .property("color", "var(--bs-gray-600) !important")
            .property("cursor", "not-allowed")
            .property("transform", "none !important"),
        CssRule::new(".history-sidebar")
            .property("width", "16rem")
            .property("background", "var(--bs-gray-900)")
            .property("border-right", "1px solid var(--bs-gray-800)")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("height", "100%"),
        CssRule::new(".sidebar-header")
            .property("padding", "1rem")
            .property("border-bottom", "1px solid var(--bs-gray-800)")
            .property("display", "flex")
            .property("justify-content", "space-between")
            .property("align-items", "center"),
        CssRule::new(".new-chat-btn")
            .property("background", "var(--bs-gray-800)")
            .property("color", "white")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "0.5rem")
            .property("padding", "0.5rem 1rem")
            .property("font-size", "0.9rem")
            .property("cursor", "pointer")
            .property("display", "flex")
            .property("align-items", "center")
            .property("gap", "0.5rem")
            .property("width", "100%")
            .property("justify-content", "center")
            .child(CssRule::new(":hover").property("background", "var(--bs-gray-700)")),
        CssRule::new(".history-list")
            .property("flex", "1")
            .property("overflow-y", "auto")
            .property("padding", "0.5rem 0")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("gap", "0.25rem"),
        CssRule::new(".history-item")
            .property("display", "flex")
            .property("align-items", "center")
            .property("justify-content", "space-between")
            .property("padding", "0.4rem 0.75rem")
            .property("color", "var(--bs-gray-300)")
            .property("text-decoration", "none")
            .property("font-size", "0.95rem")
            .property("cursor", "pointer")
            .property("border-radius", "0.5rem")
            .property("margin", "0 0.5rem")
            .child(
                CssRule::new(":hover")
                    .property("background", "var(--bs-gray-800)")
                    .property("color", "white"),
            )
            .child(
                CssRule::new(".active")
                    .property("background", "var(--bs-gray-800)")
                    .property("color", "white")
                    .property("font-weight", "bold"),
            ),
        CssRule::new(".history-item-link")
            .property("flex", "1")
            .property("overflow", "hidden")
            .property("text-overflow", "ellipsis")
            .property("white-space", "nowrap")
            .property("color", "inherit")
            .property("text-decoration", "none"),
        CssRule::new(".menu-container")
            .property("position", "relative")
            .property("display", "inline-block"),
        CssRule::new(".menu-trigger-btn")
            .property("background", "transparent")
            .property("border", "none")
            .property("color", "var(--bs-gray-500)")
            .property("cursor", "pointer")
            .property("padding", "0.25rem")
            .property("opacity", "0")
            .property("transition", "opacity 0.2s, color 0.2s")
            .child(CssRule::new(":hover").property("color", "white")),
        CssRule::new(".history-item:hover .menu-trigger-btn").property("opacity", "1"),
        CssRule::new(".menu-container:focus-within .menu-trigger-btn")
            .property("opacity", "1")
            .property("color", "white"),
        CssRule::new(".dropdown-menu")
            .property("display", "none")
            .property("position", "absolute")
            .property("right", "0")
            .property("top", "100%")
            .property("background", "var(--bs-gray-800)")
            .property("border", "1px solid var(--bs-gray-700)")
            .property("border-radius", "0.375rem")
            .property("padding", "0.25rem 0")
            .property("min-width", "7rem")
            .property("box-shadow", "0 0.5rem 1rem rgba(0,0,0,0.5)")
            .property("z-index", "1000"),
        CssRule::new(".menu-container:focus-within .dropdown-menu").property("display", "block"),
        CssRule::new(".dropdown-item")
            .property("display", "flex")
            .property("align-items", "center")
            .property("gap", "0.5rem")
            .property("width", "100%")
            .property("padding", "0.375rem 0.75rem")
            .property("background", "transparent")
            .property("border", "none")
            .property("color", "var(--bs-gray-300)")
            .property("text-align", "left")
            .property("font-size", "0.85rem")
            .property("cursor", "pointer")
            .child(
                CssRule::new(":hover")
                    .property("background", "var(--bs-gray-700)")
                    .property("color", "white"),
            ),
        CssRule::new(".dropdown-item.delete-item")
            .child(CssRule::new(":hover").property("color", "#ea868f")),
        CssRule::new(".estimates-modal")
            .property("position", "fixed")
            .property("inset", "0")
            .property("display", "none")
            .property("z-index", "9999"),
        CssRule::new(".estimates-modal.open").property("display", "flex"),
        CssRule::new(".estimates-modal-backdrop")
            .property("position", "absolute")
            .property("inset", "0")
            .property("background-color", "rgba(0,0,0,0.7) !important")
            .property("border", "none"),
        CssRule::new(".estimates-modal-content")
            .property("position", "relative")
            .property("margin", "auto")
            .property("width", "30rem")
            .property("height", "auto")
            .property("max-height", "80vh")
            .property("overflow", "hidden")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("background", "var(--bs-gray-900)")
            .property("border-radius", "0.5rem")
            .property("border", "1px solid var(--bs-gray-700)"),
        CssRule::new(".estimates-modal-content.small")
            .property("width", "30rem")
            .property("height", "auto")
            .property("max-height", "80vh"),
        CssRule::new(".estimates-modal-header")
            .property("display", "flex")
            .property("justify-content", "space-between")
            .property("align-items", "center")
            .property("padding", "1rem 1.25rem")
            .property("border-bottom", "0.0625rem solid var(--bs-gray-700)"),
        CssRule::new(".estimates-modal-title")
            .property("font-size", "1.4rem")
            .property("font-weight", "bold")
            .property("font-family", "monospace"),
        CssRule::new(".estimates-modal-close")
            .property("border", "none")
            .property("background-color", "transparent !important")
            .property("color", "var(--bs-gray-100)")
            .property("font-size", "1.4rem")
            .property("cursor", "pointer")
            .property("padding", "0.5rem")
            .property("line-height", "1"),
        CssRule::new(".estimates-modal-close:hover").property("color", "var(--bs-gray-400)"),
        CssRule::new(".estimates-modal-body")
            .property("display", "flex")
            .property("flex-direction", "column")
            .property("align-items", "center")
            .property("padding", "1.5rem")
            .property("overflow", "auto"),
        CssRule::new(".estimates-modal-body p")
            .property("text-align", "center")
            .property("margin-bottom", "1rem"),
        CssRule::new(".estimates-modal-body .model-to-delete-name")
            .property("font-family", "monospace")
            .property("font-weight", "bold")
            .property("color", "var(--bs-warning)")
            .property("margin-bottom", "2rem")
            .property("word-break", "break-all")
            .property("text-align", "center"),
        CssRule::new(".estimates-modal-body .confirm-actions")
            .property("display", "flex")
            .property("flex-direction", "row")
            .property("flex-wrap", "nowrap")
            .property("gap", "1rem")
            .property("justify-content", "center")
            .property("align-items", "center")
            .property("width", "100%"),
        CssRule::new(".estimates-modal-body .confirm-actions .button")
            .property("min-width", "5.5rem")
            .property("width", "auto")
            .property("padding", "0.4rem 0.75rem")
            .property("font-size", "0.85rem")
            .property("line-height", "1.1"),
        CssRule::new(".branch-controls")
            .property("display", "flex")
            .property("flex-direction", "row")
            .property("align-items", "center")
            .property("justify-content", "flex-end")
            .property("gap", "0.75rem")
            .property("margin-top", "0.5rem")
            .property("margin-bottom", "0.25rem")
            .property("font-size", "0.75rem")
            .property("color", "var(--bs-gray-500)")
            .property("user-select", "none")
            .property("width", "100%"),
        CssRule::new(".branch-nav")
            .property("display", "flex")
            .property("flex-direction", "row")
            .property("align-items", "center")
            .property("gap", "0.4rem")
            .property("background", "rgba(0, 0, 0, 0.2)")
            .property("padding", "0.15rem 0.25rem")
            .property("border-radius", "0.5rem")
            .property("border", "1px solid var(--bs-gray-800)"),
        CssRule::new(".branch-btn")
            .property("border", "1px solid transparent")
            .property("background-color", "transparent")
            .property("color", "var(--bs-gray-400)")
            .property("border-radius", "0.375rem")
            .property("padding", "0.15rem 0.35rem")
            .property("cursor", "pointer")
            .property("font-size", "0.7rem")
            .property("display", "inline-flex")
            .property("align-items", "center")
            .property("justify-content", "center")
            .property("gap", "0.3rem")
            .property("transition", "all 0.15s ease"),
        CssRule::new(".branch-btn:hover")
            .property("background-color", "rgba(255, 255, 255, 0.05)")
            .property("color", "var(--bs-gray-200)")
            .property("border-color", "var(--bs-gray-700)"),
        CssRule::new(".branch-info")
            .property("font-family", "monospace")
            .property("font-weight", "500")
            .property("font-size", "0.65rem")
            .property("color", "var(--bs-gray-500)")
            .property("min-width", "2.5rem")
            .property("text-align", "center"),
        CssRule::new(".regenerate-btn")
            .property("display", "none !important") // Hidden by default
            .property("border", "1px solid var(--bs-gray-700)")
            .property("background-color", "rgba(255, 255, 255, 0.03)")
            .property("padding", "0.2rem 0.6rem"),
        CssRule::new(".chat-message:last-of-type .regenerate-btn")
            .property("display", "inline-flex !important"),
        CssRule::new(".edit-btn")
            .property("display", "inline-flex !important"),
        CssRule::new(".chat-message:has(~ .message-user) .edit-btn")
            .property("display", "none !important"),
        CssRule::new(".edit-textarea")
            .property("width", "100%")
            .property("background", "transparent")
            .property("border", "none")
            .property("color", "white")
            .property("padding", "0")
            .property("font-family", "inherit")
            .property("font-size", "1.1rem")
            .property("line-height", "1.6")
            .property("resize", "none")
            .property("outline", "none")
            .property("min-height", "5rem"),
        CssRule::new(".edit-actions")
            .property("display", "flex")
            .property("justify-content", "flex-end")
            .property("gap", "0.5rem")
            .property("margin-top", "0.5rem")
            .property("border-top", "1px solid rgba(255, 255, 255, 0.1)")
            .property("padding-top", "0.5rem"),
        CssRule::new(".save-btn")
            .property("background-color", "var(--bs-primary) !important")
            .property("color", "white !important")
            .property("border", "none !important")
            .property("padding", "0.25rem 0.75rem !important")
            .property("font-size", "0.8rem !important"),
        CssRule::new(".cancel-btn")
            .property("padding", "0.25rem 0.75rem !important")
            .property("font-size", "0.8rem !important"),
    ]
}
