[[bin]]
name = "warehouse-service"
path = "src/main.rs"

[dependencies.actix-web]
workspace = true

[dependencies.base64]
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.dotenvy]
workspace = true

[dependencies.envmnt]
workspace = true

[dependencies.futures-util]
workspace = true

[dependencies.jsonwebtoken]
workspace = true

[dependencies.quench-cli]
workspace = true

[dependencies.quench-web]
workspace = true

[dependencies.rustls]
workspace = true

[dependencies.rustls-pemfile]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.sha2]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.utoipa]
workspace = true

[dependencies.utoipa-swagger-ui]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.zip]
workspace = true

[package]
categories = ["development-tools"]
description = "Warehouse - storage service"
keywords = ["development", "tools"]
name = "warehouse-service"
version = "0.1.2"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true
