[package]
name = "quench-srv"
version = "0.1.6"
edition.workspace = true
authors.workspace = true
description = "Quench - simple server framework"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[lib]
name = "quench_srv"
path = "src/lib.rs"

[dependencies]
actix-service.workspace = true
actix-web.workspace = true
chrono.workspace = true
envmnt.workspace = true
futures-util.workspace = true
jsonwebtoken.workspace = true
quench-cli.workspace = true
quench-web.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
