[package]
name = "forge-toolbox"
version = "0.1.5"
edition = { workspace = true }
authors = { workspace = true }
description = "Forge Toolbox - monitor and self-update Forge installables"
keywords = ["development", "tools", "forge"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[[bin]]
name = "forge-toolbox"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
quench-cli = { workspace = true }
semver = { workspace = true }
