[package]
name = "switchboard-service"
version = "0.4.18"
edition = { workspace = true }
authors = { workspace = true }
description = "Switchboard - dashboard/management service"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[lib]
name = "switchboard_service"
path = "src/lib.rs"

[[bin]]
name = "switchboard-service"
path = "src/main.rs"

[dependencies]
actix-web = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
envmnt = { workspace = true }
futures-util = { workspace = true }
gguf = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
quench-auth = { workspace = true }
quench-db = { workspace = true }
quench-starter = { workspace = true }
quench-web = { workspace = true }
quench-web-components = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
