[[bin]]
name = "riveter"
path = "src/main.rs"

[dependencies.anyhow]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.dotenvy]
workspace = true

[dependencies.minijinja]
workspace = true

[dependencies.quench-cli]
workspace = true

[dependencies.regex]
workspace = true

[dependencies.rustyline]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_yaml]
workspace = true

[dependencies.toml]
workspace = true

[lib]
name = "riveter"
path = "src/lib.rs"

[package]
categories = ["development-tools"]
description = "Riveter – k8s support tool, powered by Rust and minijinja."
exclude = ["**/*.rs.bk", ".gitignore", "target", "Cargo.lock"]
keywords = ["development", "tools"]
name = "riveter"
version = "0.1.2"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true
