[[bin]]
name = "welder"
path = "src/main.rs"

[build-dependencies.serde]
workspace = true

[build-dependencies.toml]
workspace = true

[dependencies.adk-core]
workspace = true

[dependencies.adk-model]
features = ["ollama"]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.dotenvy]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.shlex]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.toml]
workspace = true

[package]
categories = ["development-tools"]
description = "Welder - a multi-agent execution engine for building, routing, and coordinating structured LLM workflows."
keywords = ["development", "tools"]
name = "welder"
version = "0.1.1"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true
