[[bin]]
name = "warehouse"
path = "src/main.rs"

[dependencies.anyhow]
workspace = true

[dependencies.base64]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.quench-cli]
workspace = true

[dependencies.reqwest]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.toml]
workspace = true

[package]
categories = ["development-tools"]
description = "Warehouse - cli tool"
keywords = ["development", "tools"]
name = "warehouse-cli"
version = "0.1.1"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true
