[package]
name = "sage-service"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
description = "Sage - AI workspace service"
keywords = ["ai", "assistant", "development", "tools"]
categories = ["asynchronous", "development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
async-stream = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
envmnt = { workspace = true }
futures-util = { workspace = true }
quench-srv = { workspace = true }
quench-web = { workspace = true }
regex = { workspace = true }
dashmap = { version = "6.1" }
uuid = { workspace = true, features = ["v4"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
