[package]
name = "sage-service"
version = "0.1.9"
edition = { workspace = true }
authors = { workspace = true }
description = "Sage - AI workspace service"
keywords = ["ai", "assistant", "development", "tools"]
categories = ["asynchronous", "development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[dependencies]
actix-multipart = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
envmnt = { workspace = true }
futures-util = { workspace = true }
pdf-extract = { workspace = true }
pulldown-cmark = { workspace = true }
quench-auth = { workspace = true }
quench-cache = { workspace = true }
quench-client = { workspace = true }
quench-config = { workspace = true }
quench-db = { workspace = true }
quench-starter = { workspace = true }
quench-web = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
urlencoding = { workspace = true }
