[[bin]]
name = "anvil"
path = "src/main.rs"

[dependencies.anyhow]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.crossterm]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.toml]
workspace = true

[dependencies.walkdir]
workspace = true

[dependencies.which]
workspace = true

[lib]
name = "anvil"
path = "src/lib.rs"

[package]
categories = ["development-tools"]
description = "Anvil CLI - workspace build tools for cargo projects"
keywords = ["development", "tools"]
name = "anvil"
version = "0.1.2"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true
